### ISSUE TITLE
Srcreen is black and the program dosent work like it used to

### ISSUE THREAD

**Issue by kbooom1273** [carboncopies/BrainGenix-ERS#147]
Progam used to wokr and was very  fu n to use, BUT NOW IT WANTS ME TO INSTAL A SNAKE!!!  Specificly 39 of them. I folled the intruction of reinstalling it and stil donsent work, very sad miss  
@datacrystals you helped me before on march 5th 2022, I am once agian asking for your help. ![Capture](https://user-images.githubusercontent.com/96459055/162663741-4ff5475a-24a0-4f69-9eee-465304bca3db.PNG)

**Comment by datacrystals** [comment]
Hmm, that's not good. I was hoping that pybind11 would copy the libraries for python into the binaries directory but it appears not. For now, try installing python 3.9 (the version that this was compiled with) and see if that works. I'll work on getting it to copy the python libraries properly in the mean time.

**Comment by kbooom1273** [comment]
Very happy to listen you are fixing it. I instelled then python 3.9.12 and put all the files in the binaries folder, IT wokr agian. This pleases me, 👍 be carefull snakes are dangorous ( this python stuff is very epic) 🙏 👏 👏 
https://www.python.org/downloads/release/python-3912/

**Comment by datacrystals** [comment]
Alright, so I was hoping that this would be a quick fix, however, we're going to have to build python with so it can be part of the binaries. This is going to take a while to figure out, so I'll get back to you tomorrow or so to have a solution.
