### ISSUE TITLE
Adding Folders To Scene Tree

### ISSUE THREAD

**Issue by rachcent** [carboncopies/BrainGenix-ERS#204]
Implementing folders into the scene tree would be nice to organize and separate assets in the scene.

Different folders:

- lights
- camera
- ground
- Etc. 

THANK YOUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUU!!!!!!!!!!!!!!!!!!!!111111111111

**Comment by datacrystals** [comment]
Thanks for the feature request, working on it now.

**Comment by datacrystals** [comment]
Alright, here's what I've got so far:

![Screenshot_20220512_013344](https://user-images.githubusercontent.com/49183477/167974243-01088630-0c7d-498a-8b9d-e6ab1b7c6847.png)

Was this what you had in mind? Additionally, would you rather that they start out closed or open?

**Comment by datacrystals** [comment]
Based on the discord convo, closing as we decided to leave them closed by default. Feel free to reopen if any issues occur.
