### ISSUE TITLE
Lines, Lines Everywhere!

### ISSUE THREAD

**Issue by kbooom1273** [carboncopies/BrainGenix-ERS#225]
![image](https://user-images.githubusercontent.com/96459055/174931078-fa2b2fbb-0edd-406d-abad-0cb9ac3aace9.png)
When messing with the lighting, objects get lots of lines in areas where there should be shadows. How do I fix this? (Sorry if my English is bad, I'm learning.)

**Comment by datacrystals** [comment]
I'm sorry to hear you're having issues with ERS. I think this might be caused by shadow bias issues - I'll look into it, and let you know when I've got a patch that might be able to fix it for you.

BTW, your English is great :)

**Comment by datacrystals** [comment]
@kbooom1273 Alright, it should be working now, if not please feel free to reopen.
