### ISSUE TITLE
Shadows are in places where they shouldn't be.

### ISSUE THREAD

**Issue by kbooom1273** [carboncopies/BrainGenix-ERS#226]
![image](https://user-images.githubusercontent.com/96459055/174931863-6b7c148d-a60b-40e3-95f5-73fcc14545eb.png)
The one circled in red is casting a dumpster shadow, but there is no dumpster.(GASP) The light circled in blue is working properly. This mystery shadow showed up after I duplicated it. I believe shadow is the soul left behind from a previous dumpster, THAT WAS MURDERED( DUN DUN DUNN) Will this dumpster murder be solved or is it something else?

**Comment by datacrystals** [comment]
@kbooom1273 Apologies for the delay - I was working on the other issue you opened.

Alright, let's solve this murder-mystery... I suspect that when copying the Light class, I might've forgotten to tell the shadow system to create a new shadow map for that light so it's referencing the one created for the light it was duplicated from.

As always, I'll let you know when I think I've fixed the issue.

**Comment by datacrystals** [comment]
@kbooom1273 Alright, this should be fixed now, feel free to reopen if not. Unfortunately (or fortunately, depending on how you look at it), there was no murder mystery here - just forgot to initialize the new depth maps.
