### ISSUE TITLE
Shadows are acting up again

### ISSUE THREAD

**Issue by kbooom1273** [carboncopies/BrainGenix-ERS#231]
![image](https://user-images.githubusercontent.com/96459055/175457777-5121f4cd-21e0-4e9d-9457-4b208342f3c6.png)
Shadows are weird, but not this weird. How did this happen? Is this a shader bug or shadow bug? This happens only in the corner of the viewport on objects with shadows.

**Comment by datacrystals** [comment]
@kbooom1273 Hmm, that's odd, can you try disabling the shadow map filtering in the "Renderer Settings" window? I'm suspecting that this is a filtering issue but that'll let us know for sure.
