### ISSUE TITLE
Viewport input not working when multipole are active

### ISSUE THREAD

**Issue by kbooom1273** [carboncopies/BrainGenix-ERS#67]
I added 2 extra viewports and rotation broke on viewport 1 and 2, but vp3 continued to rotate when given input.

**Comment by datacrystals** [comment]
Hi, thanks for your bug report.
I'll take a look at this after I resolve the gizmo Viewport issue.
I think that this might be caused by the inputprocessor class but I'll let you know when I get it resolved.

**Comment by datacrystals** [comment]
Alright, it should be fixed. I'll close this for now but feel free to re-open if you still have the issue.
